[package]
name = "vrf-poker-activity"
version = "0.1.0"
edition = "2021"
authors = ["Kaloyan <gangov1@gmail.com>", "Archana <archanav1929@gmail.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
